KIN-123 List of attachment files
surfstudio/ios-kinescope-sdk pull request #34
Opened 2021-04-07 10:11 UTC by ngagarinov

## Changes

- Add "Download all" button in SideMenuBar with configs for it. Also threw delegate methods for it.
- Fill list of attachments
- Add new SideMenu cell type with description label.

## How to test?

- Open video with Tambi and Rustam. Open attachments.

2021-04-07 13:56 UTC, artemiiShabanov commented on Sources/KinescopeSDK/View/Player/Configuration/KinescopeSideMenuBarConfiguration.swift
> +    ///   - downloadAllColor: Color of Download all button
А downloadAllHighlightedColor?

2021-04-07 21:14 UTC, artemiiShabanov commented on Sources/KinescopeSDK/View/Player/KinescopePlayerViewDelegate.swift
> +    func didSelectDownloadAll(for title: String)
Давай разделять интерфейсы мб - в отдельный это дело все

2021-04-07 21:17 UTC, artemiiShabanov commented on Sources/KinescopeSDK/View/Player/Configuration/KinescopeSideMenuBarConfiguration.swift
> +                downloadAllHighlightedColor: UIColor,
Давай попробуем уйти от конкретных имен и прийти к чему-то более обезличенному

2021-04-07 21:17 UTC, artemiiShabanov commented on Sources/KinescopeSDK/View/Player/KinescopePlayerView.swift
> +            model = .init(title: title, isRoot: false, isDownloadable: false, items: [])
И здесь вот тоже к более обезличенному прийти - хотя бы String? какой-нибудь

2021-04-07 21:18 UTC, artemiiShabanov commented on Sources/KinescopeSDK/Player/KinescopeVideoPlayer.swift
> +        bcf.countStyle = .file
Это что? Не должно быть в отдельной сущности?

2021-04-07 21:18 UTC, artemiiShabanov commented on Sources/KinescopeSDK/View/Player/SideMenu/Cells/DescriptionCell.swift
> +    override func setHighlighted(_ highlighted: Bool, animated: Bool) {
Не  // MARK: - Lifecycle

2021-04-07 21:20 UTC, artemiiShabanov commented on Sources/KinescopeSDK/View/Player/SideMenu/SideMenu.swift
> +    func downloadAllTapped(for title: String)
тоже обезличить

2021-04-07 21:20 UTC, artemiiShabanov commented on Sources/KinescopeSDK/View/Player/SideMenu/SideMenu.swift
> +    func downloadAllTapped(for title: String) {
НУ и тут

2021-04-07 21:22 UTC, artemiiShabanov requested changes
Requesting changes

2021-04-08 06:36 UTC, ngagarinov commented on Sources/KinescopeSDK/Player/KinescopeVideoPlayer.swift
> +        bcf.countStyle = .file
Это конвертация байтов из int в нужный String формат, типа мегабайты, килобайты и прочее. А разве должно? По сути и так отдельная сущность, просто с конфигурацией

2021-04-08 06:44 UTC, artemiiShabanov commented on Sources/KinescopeSDK/Player/KinescopeVideoPlayer.swift
> +        bcf.countStyle = .file
Плеер сущность?

2021-04-08 06:47 UTC, artemiiShabanov commented on Sources/KinescopeSDK/Player/KinescopeVideoPlayer.swift
> +        bcf.countStyle = .file
Наверное все формирование items хочется отдельно

2021-04-08 09:38 UTC, artemiiShabanov approved these changes

2021-04-08 12:24 UTC, drxlx approved these changes

2021-04-08 12:39 UTC, merged