[KIN-124, KIN-125, KIN-126] attachment downloader
surfstudio/ios-kinescope-sdk pull request #38
Opened 2021-04-12 07:40 UTC by ngagarinov

## Changes

- Add FileService and unit tests for it
- Add AttachmentDownloader, unit test for it and documentation 
- Add start downloading attachment when it was selected
## How to test?

- mostly unit-tests

2021-04-12 07:50 UTC, artemiiShabanov commented on Sources/KinescopeSDK/Manager/AttachmentDownloader.swift
> +            return URL(fileURLWithPath: "")
Норм ли это? Мб nil лучше?

2021-04-12 07:50 UTC, artemiiShabanov commented on Sources/KinescopeSDK/Manager/AttachmentDownloader.swift
> +            try? FileManager.default.createDirectory(at: attachmentsUrl, withIntermediateDirectories: false, attributes: nil)
А мб если ошибка - стоит тоже nil вернуть

2021-04-12 07:53 UTC, ngagarinov commented on Sources/KinescopeSDK/Manager/AttachmentDownloader.swift
> +            return URL(fileURLWithPath: "")
Ну по идее директория документов точно должна быть на телефоне, я хз, не хотелось опшинолы плодить

2021-04-12 08:03 UTC, artemiiShabanov commented on Sources/KinescopeSDK/Service/FileService.swift
> +        self.session = session
Метод для тестов?)))

2021-04-12 08:04 UTC, ngagarinov commented on Sources/KinescopeSDK/Service/FileService.swift
> +        self.session = session
да, там иначе не протестировать, ну разве что в открытой проперти

2021-04-12 09:15 UTC, ngagarinov commented on Sources/KinescopeSDK/Manager/AttachmentDownloader.swift
> +            try? FileManager.default.createDirectory(at: attachmentsUrl, withIntermediateDirectories: false, attributes: nil)
посмотрел, можно и так сделать, поправлю тогда в обоих случаях

2021-04-12 10:12 UTC, artemiiShabanov commented on Sources/KinescopeSDK/Service/FileService.swift
> +        self.session = session
А мб как то через extension там?

2021-04-12 11:07 UTC, artemiiShabanov commented on Sources/KinescopeSDKTests/Service/Common/FileServiceTests.swift
> +    func testRestoreTasks() {
Кажется что должен проверяться метод restore, но он не проверяется

2021-04-12 11:22 UTC, drxlx requested changes
хотелось бы еще тест на то что в ФС появился файл, что он читается из ФС и что очищается корректно

2021-04-12 11:33 UTC, artemiiShabanov commented on Sources/KinescopeSDKTests/Mock/MockDownloadURLSession.swift
> +    var state: TaskState
Кажется неправильно, что у state задачи присущ всей сессии

2021-04-12 11:41 UTC, ngagarinov commented on Sources/KinescopeSDK/Service/FileService.swift
> +    init(idsStorage: IDsStorage = IDsUDStorage()) {
ну если вдруг совпадут, то кажется дернется случайное значение

2021-04-12 12:14 UTC, ngagarinov commented on Sources/KinescopeSDK/Service/FileService.swift
> +    init(idsStorage: IDsStorage = IDsUDStorage()) {
по идее мы читаем и сохраняем по урлу, урлы уж точно будут уникальными, учитывая сигнатуру и expired

2021-04-12 12:21 UTC, ngagarinov commented on Sources/KinescopeSDKTests/Mock/MockDownloadURLSession.swift
> +    var state: TaskState
Обсудили, будет исправлено в KIN-119

2021-04-12 12:22 UTC, ngagarinov commented on Sources/KinescopeSDK/Player/KinescopeVideoPlayer.swift
> -                                     level: KinescopeLoggerLevel.player)
Ну мы вроде стартуем запрос в сеть, ну наверное странно, да, поменяю

2021-04-12 13:03 UTC, ngagarinov commented
> хотелось бы еще тест на то что в ФС появился файл, что он читается из ФС и что очищается корректно

написал тест testCacheConsistency, в котором сначала грузится файл, проверяется его наличие, достается путь до файла(непонятно с чем именно сравнивать, поэтому просто проверяю, что не нил), после чего удаляется и снова проверяется путь до файла.

2021-04-12 14:30 UTC, drxlx approved these changes

2021-04-15 08:37 UTC, artemiiShabanov approved these changes

2021-04-15 11:15 UTC, merged