Add service layer
surfstudio/ios-kinescope-sdk pull request #4
Opened 2021-03-23 15:46 UTC by drxlx

## Changes

- Add transport for encapsulation `URLSession.dataTask`
- Add `RequestBuilder` for building `URLRequest` with **path**, **method**, **headers**, **query parameters** and **body**
- Add `VideosService` for getting all videos and video by id
- Add `AssetsService` for getting asset url
- Add `ServerError` for handling [server errors](https://documenter.getpostman.com/view/10589901/TVCcXpNM#errors)
- Add `Transport` and `RequestBuilderTests`
- Change `Inspector` and `set(config:)` and use DI for service
- Add models for request but models not complete

## How to test?

- Open `Tests.swift` and run

2021-03-23 18:12 UTC, NullIsOne requested changes
Не совсем такое я ожидал, но так даже лучше.
Сеть в отдельных сервисах и отдельные верхе-уровневые публичные сервисы (типа `Inspector`) будут использовать их для работы с сетью. Огонь
Лайк за тесты.

Надо немного прокачать работу с `Codable` и сольем (см комменты)

2021-03-23 18:12 UTC, NullIsOne commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideo.swift
> +        case projectId = "project_id"
и обратное в `RequestBuilder` добавить можно
`encoder.keyEncodingStrategy = .convertToSnakeCase`

2021-03-24 03:41 UTC, NullIsOne commented on Sources/KinescopeSDKTests/Tests.swift
> +//swiftlint:disable all
Кстати, по поводу этого игнора. Слишком хитро отключать все правила.

Можно отключать конкретное правило
`//swiftlint:disable force_unwrapping`
это подействует в рамках файла
в конце файла можно не вызывать `swiftlint:enable`

2021-03-24 12:01 UTC, drxlx commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideo.swift
> +        case projectId = "project_id"
да, забыл совсем про это, спасибо

2021-03-24 12:10 UTC, drxlx commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideo.swift
> +    let id: String
поправил

2021-03-24 12:10 UTC, drxlx commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideo.swift
> +    public init(from decoder: Decoder) throws {
уже не помню, возможно просто так добавлял. поправил

2021-03-24 12:10 UTC, drxlx commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideo.swift
> +    let poster: KinescopeVideoPoster
Написал в чат

2021-03-24 12:11 UTC, drxlx commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideoAsset.swift
> +    let id: String
поправил

2021-03-24 12:11 UTC, drxlx commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideo.swift
> +    public init(id: String,
в тестах нужен был, но в финальную версию это не вошло) поправил

2021-03-24 12:11 UTC, drxlx commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideo.swift
> +        return lhs.id == rhs.id
в тестах нужно было, убрал

2021-03-24 12:11 UTC, drxlx commented on Sources/KinescopeSDK/Service/Common/Factory.swift
> +protocol Factory {
удалил

2021-03-24 12:12 UTC, drxlx commented on Sources/KinescopeSDKTests/Tests.swift
> +//swiftlint:disable all
тут либо нужно какие-то правила отдельные для тестов писать, либо просто отключить на весь файл, потому что большинство правил отстреливают в тестах

2021-03-24 12:16 UTC, NullIsOne commented on Sources/KinescopeSDKTests/Tests.swift
> +//swiftlint:disable all
ок
попробуем это через конфиг линтера поправить
отдельные правила для тестов
потом уберем

2021-03-24 12:17 UTC, NullIsOne approved these changes

2021-03-24 12:17 UTC, merged