Kin 19 video list
surfstudio/ios-kinescope-sdk pull request #6
Opened 2021-03-24 17:32 UTC by NullIsOne

## Changes

- Add `Inpector` implementation. 
- Add unit tests with mocked `VideosApiClient`
- Add `MetaResponse` to get meta-info
- ...

## Open questions

- Tested on debug. Requesting of multiple pages will be added in next task with `ViewController` implementation.
- ...

## How to test?

- Set apiKey in `AppDelegate`
- Request list like
```
Kinescope.shared.inspector.list(request: .init(page: 1),
                                        onSuccess: { result in
                                            print("KIN result \(result)")
                                        }, onError: { error in
                                            print("KIN error \(error)")
                                        })
```
- Check logs

2021-03-24 19:30 UTC, drxlx requested changes

2021-03-24 19:30 UTC, drxlx commented on Sources/KinescopeSDK/Service/Common/Transport.swift
> +    func perform<D: Codable, M: Codable>(request: URLRequest, completion: @escaping (Result<MetaResponse<D, M>, Error>) -> Void) {
может простой коммент добавить что метод для работы с запросами с пагинацией, а в другом что без пагинации?

2021-03-24 19:30 UTC, drxlx commented on Sources/KinescopeSDK/Service/VideosService.swift
> +protocol VideosApiClient {
Может лучше `VideoService` и `VideoNetworkService` или что-то в этом духе?

2021-03-24 19:30 UTC, drxlx commented on Sources/KinescopeSDK/Protocols/KinescopeInspectable.swift
> +              onSuccess: @escaping (([KinescopeVideo], KinescopeMetaData?)) -> Void,
может лучше вместо двух блоков использовать `Result<Data, Error>` по аналогии с сервисами ?

2021-03-24 19:30 UTC, drxlx commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideoRequest.swift
> +    public init(page: Int, perPage: Int = 5, order: String? = nil) {
может где-то в комментах пометить что значение по умолчанию 5?

2021-03-24 19:30 UTC, drxlx commented on Sources/KinescopeSDK/Manager/Inspector.swift
> +    static func from(error: Error) -> KinescopeInspectError {
может это спрятать в файл`KinescopeInspectError`?

2021-03-25 05:50 UTC, NullIsOne commented on Sources/KinescopeSDK/Manager/Inspector.swift
> +    static func from(error: Error) -> KinescopeInspectError {
Этот маппинг - часть логики инспектора. По этой же причине приватно сделан extension.

Сделал через статичную функцию `Inspector.parse(error: Error) -> KinescopeInspectError ` чтобы не было желания куда-то перенести.

2021-03-25 05:54 UTC, NullIsOne commented on Sources/KinescopeSDK/Protocols/KinescopeInspectable.swift
> +              onSuccess: @escaping (([KinescopeVideo], KinescopeMetaData?)) -> Void,
В перезентерах и контроллерах, в общем на слое представления удобнее иметь раздельные колбэки.
Ошибки обрабатываются отдельно, а не вместе с результатом.
И тип параметра так короче.
Ну это мое мнение.

Если будут аргументы, могу исправить)

2021-03-25 05:54 UTC, NullIsOne commented on Sources/KinescopeSDK/Service/VideosService.swift
> +protocol VideosApiClient {
Готово

2021-03-25 05:54 UTC, NullIsOne commented on Sources/KinescopeSDK/Models/Videos/KinescopeVideoRequest.swift
> +    public init(page: Int, perPage: Int = 5, order: String? = nil) {
Добавил

2021-03-25 06:00 UTC, NullIsOne commented on Sources/KinescopeSDK/Service/Common/Transport.swift
> +    func perform<D: Codable, M: Codable>(request: URLRequest, completion: @escaping (Result<MetaResponse<D, M>, Error>) -> Void) {
пояснил

2021-03-25 11:03 UTC, drxlx approved these changes

2021-03-25 11:51 UTC, merged